version: 2
jobs:
  download-deps:
    working_directory: ~/vanish-android
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - restore_cache:
          key: deps-{{ .Revision }} 
          key: deps
      - checkout
      - run: 
          name: Install Fastlane
          command: gem install fastlane
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: deps-{{ .Revision }}
          paths:
            - ~/.gradle
            - ~/vanish-android
            - ~/.ruby-version
            - ~/.rubies/ruby-2.4.3
  build:
    working_directory: ~/vanish-android
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - restore_cache:
          key: deps-{{ .Revision }}
          key: deps
      - run: 
          name: Build APK
          command: fastlane build dest:$CIRCLE_BRANCH
      - save_cache:
          key: build-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/vanish-android/app/build/outputs
            - ~/vanish-android/app/production
#  test:
#    working_directory: ~/vanish-android
#    docker:
#      - image: circleci/android:api-26-alpha
#    steps:
#      - restore_cache:
#          key: deps-{{ .Revision }}
#          key: deps
#      - run:
#          name: Run unit tests
#          command: fastlane unitTest dest:$CIRCLE_BRANCH
  crashlytics:
    working_directory: ~/vanish-android
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - restore_cache:
          key: deps-{{ .Revision }}
          key: deps
      - restore_cache:
          key: build-{{ .Branch }}-{{ .Revision }}
      - run: 
          name: Upload to Crashlytics Beta
          command: fastlane crashlyticsUploadCircle dest:$CIRCLE_BRANCH
  deploy:
    working_directory: ~/vanish-android
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - restore_cache:
          key: deps-{{ .Revision }}
          key: deps
      - restore_cache:
          key: build-{{ .Branch }}-{{ .Revision }}
      - run: 
          name: Upload to Play Beta
          command: fastlane deployBeta
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - download-deps
#      - test:
#          requires:
#            - download-deps
      - build:
          requires:
            - download-deps
      # - integration:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only:
      #           - develop
      #           - staging
      #           - demo
      #           - master
      - crashlytics:
          requires:
            # - integration
            - build
          filters:
            branches:
              only:
                - develop
                - staging
                - demo
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master